// Copyright 2025 Medvedev Dan (https://github.com/Firegreat78)

/*
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include "infouserwindow.h"
#include "ui_infouserwindow.h"

#include "windowmanager.h"
#include "socketmanager.h"
#include "logger.h"
#include "JsonTypes.h"

#include <QCloseEvent>
#include <QShowEvent>
#include <QJsonObject>
#include <QMessageBox>

InfoUserWindow::InfoUserWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::InfoUserWindow)
{
    ui->setupUi(this);
    connect(ui->changeUsernameButton, &QPushButton::clicked, this, &InfoUserWindow::changeUsernameButtonClick);
    connect(ui->changePwordButton, &QPushButton::clicked, this, &InfoUserWindow::changePwordButtonClick);
    connect(ui->deleteAccountButton, &QPushButton::clicked, this, &InfoUserWindow::deleteAccountButtonClick);

    SocketManager& sm = SocketManager::getInstance();
    connect(sm.getSocket(), &QTcpSocket::connected, this, &InfoUserWindow::onSocketConnected);
    connect(sm.getSocket(), &QTcpSocket::disconnected, this, &InfoUserWindow::onSocketDisconnected);
    connect(sm.getSocket(), &QTcpSocket::errorOccurred, this, &InfoUserWindow::onSocketError);

    connect(&sm, &SocketManager::arrivedJSInfoUserWin, this, &InfoUserWindow::onJsonArrived);
}

InfoUserWindow::~InfoUserWindow()
{
    delete ui;
}

void InfoUserWindow::showEvent(QShowEvent *event)
{
    QMainWindow::showEvent(event);
    WindowManager& wm = WindowManager::getInstance();
    SocketManager& sm = SocketManager::getInstance();
    ui->loginInfoValueLabel->setText(wm.login);
    ui->usernameInfoValueLabel->setText(wm.username);
    ui->timestampInfoValueLabel->setText(wm.ts_account_created);

    ui->changeUsernameButton->setEnabled(SocketManager::isConnectedToServer());
    ui->changePwordButton->setEnabled(SocketManager::isConnectedToServer());
    ui->deleteAccountButton->setEnabled(SocketManager::isConnectedToServer());
}

void InfoUserWindow::closeEvent(QCloseEvent *event)
{
    QMainWindow::closeEvent(event);
}

void InfoUserWindow::hideEvent(QHideEvent *event)
{
    QMainWindow::hideEvent(event);
}

void InfoUserWindow::changeUsernameButtonClick()
{
    SocketManager& sm = SocketManager::getInstance();
    WindowManager& wm = WindowManager::getInstance();
    if (!SocketManager::isConnectedToServer())
    {
        return;
    }
    QString newUsername = ui->newUsernameLineEdit->text();
    if (newUsername == ui->usernameInfoValueLabel->text())
    {
        return;
    }
    QJsonObject js;
    js["type"] = CHANGE_USERNAME;
    js["id"] = wm.user_id;
    js["new_username"] = ui->newUsernameLineEdit->text();
    sm.sendJSON(js);
}

void InfoUserWindow::changePwordButtonClick()
{
    SocketManager& sm = SocketManager::getInstance();
    WindowManager& wm = WindowManager::getInstance();
    if (!SocketManager::isConnectedToServer())
    {
        return;
    }
    QString password1 = ui->newPwordLineEdit->text();
    QString password2 = ui->confirmNewPwordLineEdit->text();
    if (password1 != password2)
    {
        return;
    }
    QJsonObject js;
    js["type"] = CHANGE_PASSWORD;
    js["id"] = wm.user_id;
    js["new_password_hash"] = wm.sha256FromQString(password1);
    sm.sendJSON(js);
}

void InfoUserWindow::deleteAccountButtonClick()
{
    SocketManager& sm = SocketManager::getInstance();
    WindowManager& wm = WindowManager::getInstance();

    if (!sm.isConnectedToServer()) return;

    QJsonObject js;
    js["type"] = DELETE_ACCOUNT;
    js["logon_user_id"] = wm.user_id;
    sm.sendJSON(js);
}

void InfoUserWindow::onSocketConnected()
{
    ui->changeUsernameButton->setEnabled(true);
    ui->changePwordButton->setEnabled(true);
    ui->deleteAccountButton->setEnabled(true);
}

void InfoUserWindow::onSocketDisconnected()
{
    ui->changeUsernameButton->setEnabled(false);
    ui->changePwordButton->setEnabled(false);
    ui->deleteAccountButton->setEnabled(false);
}

void InfoUserWindow::onSocketError(QAbstractSocket::SocketError error)
{
    ui->changeUsernameButton->setEnabled(false);
    ui->changePwordButton->setEnabled(false);
    ui->deleteAccountButton->setEnabled(false);
}

void InfoUserWindow::onJsonArrived()
{
    Logger& logger = Logger::getInstance();
    SocketManager& sm = SocketManager::getInstance();
    std::optional<QJsonObject> js = sm.popJSON(INFOUSER_WINDOW);
    if (js.has_value()) handleJSON(js.value());
}

void InfoUserWindow::handleJSON(QJsonObject const& js)
{
    Logger& logger = Logger::getInstance();
    int const type = js["type"].toInt();

    if (type == ERROR_TYPE)
    {
        std::string const msg = std::string("Server error occured: ") +
            js["info"].toString().toStdString();;
        Logger::getInstance().log(msg);
        return;
    }
    QJsonObject response = js["response"].toObject();
    if (type == CHANGE_USERNAME) changeUsernameHandler(response);
    else if (type == CHANGE_PASSWORD) changePasswordHandler(response);
    else if (type == DELETE_ACCOUNT) deleteAccountHandler(response);
}

void InfoUserWindow::changeUsernameHandler(QJsonObject const& js)
{
    WindowManager& wm = WindowManager::getInstance();
    bool const success = (js["success"] == 1);
    if (!success) return;
    wm.username = ui->newUsernameLineEdit->text();
    ui->usernameInfoValueLabel->setText(wm.username);
    ui->newUsernameLineEdit->setText("");
    return;
}

void InfoUserWindow::changePasswordHandler(QJsonObject const& js)
{
    WindowManager& wm = WindowManager::getInstance();
    bool const success = (js["success"] == 1);
    if (!success) return;
    ui->newPwordLineEdit->setText("");
    ui->confirmNewPwordLineEdit->setText("");
}

void InfoUserWindow::deleteAccountHandler(QJsonObject const& js)
{
    WindowManager& wm = WindowManager::getInstance();
    bool const success = (js["success"] == 1);
    if (!success) return;
    wm.hideAllWindows();
    wm.showWindow("MainWindow");
}
