// Copyright 2025 Medvedev Dan (https://github.com/Firegreat78)

/*
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <memory>
#include <QMainWindow>
#include <QtNetwork>
#include <QRegularExpressionValidator>

QT_BEGIN_NAMESPACE
namespace Ui {
class MainWindow;
}
QT_END_NAMESPACE

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    MainWindow(QWidget *parent = nullptr);
    ~MainWindow();
    void customShow();
    void customHide();

protected:
    void showEvent(QShowEvent*) override;
    void closeEvent(QCloseEvent*) override;
    void hideEvent(QHideEvent*) override;

private slots:
    void loginButtonClick();
    void registerButtonClick();
    void switchStatusButtonClick();
    void tryReconnect();
    void onSocketConnected();
    void onSocketDisconnected();
    void onSocketError(QAbstractSocket::SocketError);

    void updateReconnectionLabel();
    void sendHeartBeat();

    void onJsonArrived();



private:
    Ui::MainWindow *ui;
    bool connected = false;
    bool isActive = false;
    QTimer* reconnectTimer = nullptr; // tries to reconnect to the server
    QTimer* heartbeatTimer = nullptr; // sends a heartbeat to the server
    QTimer* labelTickTimer = nullptr; // updates the label
    int secondsUntilReconnection = 0;
    QTimer* heartbeatResponseTimer = nullptr; // we give the server some time to respond to the heartbeat


    std::unique_ptr<QRegularExpressionValidator> loginValidator = nullptr;

    bool login_mode = true;

    void handle_json(QJsonObject const&);
    void loginResponseHandler(QJsonObject const&);
    void registerResponseHandler(QJsonObject const&);

};
#endif // MAINWINDOW_H
