// Copyright 2025 Medvedev Dan (https://github.com/Firegreat78)

/*
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include "messageinfo.h"

#include "windowmanager.h"


MessageInfo::MessageInfo() {}

MessageInfo::MessageInfo(int64_t id,
                         QString const& username,
                         QString const& text,
                         bool hasReply,
                         int64_t replyID,
                         QString const& replyText,
                         QString const& tsStr, // from DB
                         bool isOwnMessage,
                         QString const& lastEditedTs,
                         bool repliedMsgDeleted,
                         QString const& repliedUsername,
                         bool isReadByOther)
{
    this->id = id;
    this->username = username;
    this->text = text;
    this->hasReply = hasReply;
    this->repliedMsgDeleted = repliedMsgDeleted;
    if (!hasReply)
    {
        this->replyID = 0;
        this->replyText = "";
    }
    else if (repliedMsgDeleted) // there was an answer, but it was deleted afterwards
    {
        this->replyID = 0;
        this->replyText = "Оригинальное сообщение удалено...";
    }
    else
    {
        this->replyID = replyID;
        this->replyText = replyText.length() > 30 ? replyText.first(30)+"..." : replyText;
    }
    this->tsStr = WindowManager::convertToLocalTimeString(tsStr);
    tsDt = QDateTime::fromString(this->tsStr, "yyyy-MM-dd HH:mm:ss");
    this->isOwnMessage = isOwnMessage;

    this->lastEditedTs = lastEditedTs;
    this->repliedUsername = repliedUsername;
    this->isReadByOther = isReadByOther;
}

MessageInfo MessageInfo::fromJS(QJsonObject const& message)
{
    WindowManager& wm = WindowManager::getInstance();

    MessageInfo info(message["id"].toInteger(),
                     message["sender_username"].toString(),
                     message["content"].toString(),
                     message["has_reply"].toBool(),
                     message["reply_to_id"].isNull() ?
                         0 :
                         message["reply_to_id"].toInteger(),
                     message["reply_to_id"].isNull() ?
                         "" :
                         message["replied_message_content"].toString(),
                     message["sent_at"].toString(),
                     message["sender_id"].toInteger() == wm.user_id,
                     message["last_edited"].isNull() ?
                         "" :
                         WindowManager::convertToLocalTimeString(message["last_edited"].toString()),
                     message["replied_msg_deleted"].toBool(),
                     message["reply_to_username"].isNull() ?
                         "" :
                         "@"+message["reply_to_username"].toString(),
                     message["is_read_by_other"].toBool()
                     );
    return info;
}
