// Copyright 2025 Medvedev Dan (https://github.com/Firegreat78)

/*
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef SOCKETMANAGER_H
#define SOCKETMANAGER_H

#include <QObject>
#include <QTcpSocket>
#include <memory>
#include <vector>
#include <QQueue>
#include <QJsonObject>
#include <optional>


class SocketManager : public QObject
{
    Q_OBJECT

private:
    explicit SocketManager(QObject *parent = nullptr);
    std::unique_ptr<QTcpSocket> socket;
    QByteArray accumulated;
    QQueue<QJsonObject> mainWinQ;
    QQueue<QJsonObject> baseWinQ;
    QQueue<QJsonObject> infoUserWinQ;
    bool isConnected = false;

    void enqueue(QJsonObject const&);
    std::optional<QJsonObject> popJSMainWin();
    std::optional<QJsonObject> popJSBaseWin();
    std::optional<QJsonObject> popJSInfoUserWin();

private slots:
    void onSocketConnected();
    void onSocketDisconnected();
    void onSocketError(QAbstractSocket::SocketError);
    void onSocketReadyRead();

public:
    static constexpr int SOCKET_BUFFER = 8192;


    static SocketManager& getInstance();
    static bool isConnectedToServer();
    QTcpSocket const* getSocket();

    // this won't send an empty json
    bool sendJSON(QJsonObject const&);

    // Pop a json from an specific queue
    // 1 - main window
    // 2 - base window
    // 3 - info user window
    std::optional<QJsonObject> popJSON(int64_t const);

    // async connect
    void tryConnect();


signals: // public by default
    void arrivedJSMainWin();
    void arrivedJSBaseWin();
    void arrivedJSInfoUserWin();
};

#endif // SOCKETMANAGER_H
