// Copyright 2025 Medvedev Dan (https://github.com/Firegreat78)

/*
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef WINDOWMANAGER_H
#define WINDOWMANAGER_H

#include <QObject>
#include <QMainWindow>
#include <QMap>
#include <QRegularExpressionValidator>


// centralized class, application manager
class WindowManager : public QObject
{
    Q_OBJECT
private:
    explicit WindowManager(QObject *parent = nullptr);
    QMap<QString, QMainWindow*> windows;
public:
    // logon user id
    qint64 user_id;

    // Chat ID we selected. If private chat is not yet initialized, look at the user_id_2 just in case
    qint64 chat_id = 0;

    // user id we selected a private chat with
    qint64 user_id_2 = 0;

    //
    QString login;
    QString username;
    QString ts_account_created;
    std::unique_ptr<QRegularExpressionValidator> loginValidator;
public:
    static WindowManager& getInstance();
    void registerWindow(QString const&, QMainWindow*);
    void showWindow(QString const&);
    void hideWindow(QString const&);
    void hideAllWindows();
    int windowIsShown(QString const&);
    QMainWindow* getWindow(QString const&);
    QString sha256FromQString(QString const&);
    static QString convertToLocalTimeString(QString const&);

signals:
};

#endif // WINDOWMANAGER_H
